name: Update README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Update README
        run: |
          dart run build_readme.dart

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout main
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Updated README"
            git push origin main --force
          fi
